import { JSX } from "react";
import {
  FaWifi,
  FaSwimmingPool,
  FaCoffee,
  FaConciergeBell,
  FaWheelchair,
  FaUmbrellaBeach,
  FaBicycle,
  FaTv,
  FaSuitcaseRolling,
  FaBell,
  FaRegClock,
  FaUserShield,
  FaBeer,
  FaSmoking,
  FaSpa,
  FaBed,
  FaDoorOpen,
  FaParking,
  FaUtensils,
  FaPeopleArrows,
  FaShower,
  FaSnowflake,
  FaDumbbell,
  FaCar,
  FaPlane,
  FaBus,
  FaTrain,
  FaShip,
  FaTaxi,
  FaHotel,
  FaShoppingCart,
  FaGift,
  FaChild,
  FaBaby,
  FaDog,
  FaCat,
  FaLeaf,
  FaRecycle,
  FaSolarPanel,
  FaWind,
  FaFireExtinguisher,
  FaFirstAid,
  FaPhone,
  FaEnvelope,
  FaMapMarkerAlt,
  FaGlobe,
  FaLanguage,
  FaMoneyBillWave,
  FaCreditCard,
  FaExchangeAlt,
  FaLock,
  FaUnlock,
  FaEye,
  FaEyeSlash,
  FaVolumeUp,
  FaVolumeMute,
  FaSun,
  FaMoon,
  FaCloud,
  FaCloudRain,
  FaThermometerEmpty,
  FaThermometerQuarter,
  FaThermometerHalf,
  FaThermometerThreeQuarters,
  FaThermometerFull,
} from "react-icons/fa";

export const amenityIcons: { [key: string]: JSX.Element } = {
  "Free WiFi": <FaWifi />,
  "Free Wi-Fi": <FaWifi />,
  "WiFi": <FaWifi />,
  "Internet": <FaWifi />,
  "High-speed Internet": <FaWifi />,
  "Swimming Pool": <FaSwimmingPool />,
  "Pool": <FaSwimmingPool />,
  "Outdoor Pool": <FaSwimmingPool />,
  "Indoor Pool": <FaSwimmingPool />,
  "Pool umbrellas": <FaUmbrellaBeach />,
  "Fence around pool": <FaUmbrellaBeach />,
  "Coffee/tea in common areas": <FaCoffee />,
  "Coffee": <FaCoffee />,
  "Tea": <FaCoffee />,
  "Breakfast available (surcharge)": <FaUtensils />,
  "Breakfast": <FaUtensils />,
  "Snack bar/deli": <FaUtensils />,
  "Restaurant": <FaUtensils />,
  "Bar": <FaBeer />,
  "Number of bars/lounges - 1": <FaBeer />,
  "Lounge": <FaBeer />,
  "Concierge services": <FaConciergeBell />,
  "Concierge": <FaConciergeBell />,
  "Porter/bellhop": <FaBell />,
  "Bellhop": <FaBell />,
  "24-hour front desk": <FaRegClock />,
  "Front Desk": <FaRegClock />,
  "Express check-out": <FaDoorOpen />,
  "Check-out": <FaDoorOpen />,
  "Tours/ticket assistance": <FaConciergeBell />,
  "Tour Desk": <FaConciergeBell />,
  "Wedding services": <FaConciergeBell />,
  "Wedding": <FaConciergeBell />,
  "Wheelchair accessible": <FaWheelchair />,
  "Wheelchair accessible (may have limitations)": <FaWheelchair />,
  "Braille or raised signage": <FaWheelchair />,
  "Accessible": <FaWheelchair />,
  "Bicycle rentals nearby": <FaBicycle />,
  "Bicycle": <FaBicycle />,
  "Airport Shuttle": <FaPlane />,
  "Shuttle": <FaCar />,
  "Car Rental": <FaCar />,
  "Taxi Service": <FaTaxi />,
  "Bus Stop": <FaBus />,
  "Train Station": <FaTrain />,
  "Port": <FaShip />,
  "Television in common areas": <FaTv />,
  "TV": <FaTv />,
  "Television": <FaTv />,
  "Luggage storage": <FaSuitcaseRolling />,
  "Luggage": <FaSuitcaseRolling />,
  "Storage": <FaSuitcaseRolling />,
  "Laundry facilities": <FaSuitcaseRolling />,
  "Laundry": <FaSuitcaseRolling />,
  "Dry cleaning/laundry service": <FaSuitcaseRolling />,
  "Dry Cleaning": <FaSuitcaseRolling />,
  "Safe-deposit box at front desk": <FaUserShield />,
  "Safe": <FaUserShield />,
  "Security": <FaUserShield />,
  "Fire Extinguisher": <FaFireExtinguisher />,
  "First Aid": <FaFirstAid />,
  "Emergency": <FaFirstAid />,
  "Full-service spa": <FaSpa />,
  "Spa": <FaSpa />,
  "Spa treatment room(s)": <FaSpa />,
  "Wellness": <FaSpa />,
  "Massage": <FaSpa />,
  "Change of bed sheets (on request)": <FaBed />,
  "Bed Sheets": <FaBed />,
  "Change of towels (on request)": <FaBed />,
  "Towels": <FaBed />,
  "Bed": <FaBed />,
  "Conference space": <FaPeopleArrows />,
  "Conference": <FaPeopleArrows />,
  "Conference space size (meters) - 5665": <FaPeopleArrows />,
  "Conference space size (feet) - 60981": <FaPeopleArrows />,
  "Business Center": <FaPeopleArrows />,
  "Meeting Room": <FaPeopleArrows />,
  "Free self parking": <FaParking />,
  "Free valet parking": <FaParking />,
  "Covered parking": <FaParking />,
  "Uncovered parking": <FaParking />,
  "secured parking": <FaParking />,
  "Parking": <FaParking />,
  "Valet": <FaParking />,
  "Designated smoking areas": <FaSmoking />,
  "Smoking": <FaSmoking />,
  "Non-smoking": <FaSmoking />,
  "Gym": <FaDumbbell />,
  "Fitness Center": <FaDumbbell />,
  "Workout": <FaDumbbell />,
  "Exercise": <FaDumbbell />,
  "Air Conditioning": <FaSnowflake />,
  "AC": <FaSnowflake />,
  "Heating": <FaThermometerHalf />,
  "Climate Control": <FaThermometerHalf />,
  "Private Bathroom": <FaShower />,
  "Bathroom": <FaShower />,
  "Shower": <FaShower />,
  "Bathtub": <FaShower />,
  "Children Welcome": <FaChild />,
  "Kids Club": <FaChild />,
  "Baby Sitting": <FaBaby />,
  "Family Room": <FaChild />,
  "Pet Friendly": <FaDog />,
  "Dogs Allowed": <FaDog />,
  "Cats Allowed": <FaCat />,
  "Eco-friendly": <FaLeaf />,
  "Green": <FaLeaf />,
  "Recycling": <FaRecycle />,
  "Solar Power": <FaSolarPanel />,
  "Wind Power": <FaWind />,
  "Phone": <FaPhone />,
  "Email": <FaEnvelope />,
  "Internet Access": <FaWifi />,
  "Location": <FaMapMarkerAlt />,
  "Address": <FaMapMarkerAlt />,
  "Nearby": <FaMapMarkerAlt />,
  "International": <FaGlobe />,
  "Multi-language": <FaLanguage />,
  "Translation": <FaLanguage />,
  "Credit Card": <FaCreditCard />,
  "Cash": <FaMoneyBillWave />,
  "Currency Exchange": <FaExchangeAlt />,
  "ATM": <FaCreditCard />,
  "Private": <FaLock />,
  "Lock": <FaLock />,
  "Unlock": <FaUnlock />,
  "Privacy": <FaEye />,
  "View": <FaEye />,
  "Hidden": <FaEyeSlash />,
  "Sound": <FaVolumeUp />,
  "Mute": <FaVolumeMute />,
  "Audio": <FaVolumeUp />,
  "Sun": <FaSun />,
  "Moon": <FaMoon />,
  "Cloud": <FaCloud />,
  "Rain": <FaCloudRain />,
  "Snow": <FaSnowflake />,
  "Temperature": <FaThermometerHalf />,
  "Hot": <FaThermometerFull />,
  "Cold": <FaThermometerEmpty />,
  "Warm": <FaThermometerQuarter />,
  "Cool": <FaThermometerThreeQuarters />,
  "Shopping": <FaShoppingCart />,
  "Gift Shop": <FaGift />,
  "Store": <FaShoppingCart />,
  "Market": <FaShoppingCart />,
  "Hotel": <FaHotel />,
  "Resort": <FaHotel />,
  "Lodge": <FaHotel />,
  "Inn": <FaHotel />,
}; 